FROM node:22.14.0 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx quasar build

FROM nginx:stable-alpine

COPY docker/frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/spa /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]